#pragma once

//
// Features
//

#cmakedefine01 CXXSERVER_WITH_DEV_VALUES
#cmakedefine01 CXXSERVER_WITH_TESTS

//
// Build options
//

#cmakedefine01 CXXSERVER_WITH_ASAN
#cmakedefine01 CXXSERVER_WITH_LSAN
#cmakedefine01 CXXSERVER_WITH_MSAN
#cmakedefine01 CXXSERVER_WITH_SCOV
#cmakedefine01 CXXSERVER_WITH_TSAN
#cmakedefine01 CXXSERVER_WITH_UBSAN
#cmakedefine01 CXXSERVER_WITH_LIBCXX
#cmakedefine01 CXXSERVER_WITH_FAST_OPTIMIZATION
#cmakedefine01 CXXSERVER_WITH_NATIVE_ARCHITECTURE
#cmakedefine01 CXXSERVER_WITH_SECURE_ALLOCATOR
#cmakedefine01 CXXSERVER_WITH_STACK_PROTECTOR

//
// Names
//

#define CXXSERVER_FRAMEWORK_NAME   "@CXXSERVER_FRAMEWORK_NAME@"
#define CXXSERVER_APPLICATION_NAME "@CXXSERVER_APPLICATION_NAME@"

//
// Version
//

#define CXXSERVER_VERSION_MAJOR @CXXSERVER_VERSION_MAJOR@
#define CXXSERVER_VERSION_MINOR @CXXSERVER_VERSION_MINOR@
#define CXXSERVER_VERSION_PATCH @CXXSERVER_VERSION_PATCH@
#define CXXSERVER_VERSION       "@CXXSERVER_VERSION@"
